#!/usr/bin/env bash
set -euo pipefail

TARGET_FILE="${1:-.env.production}"

if [[ -e "$TARGET_FILE" ]]; then
  echo "Refusing to overwrite existing file: $TARGET_FILE" >&2
  echo "Pass a different path or remove the file first." >&2
  exit 1
fi

read -r -p "Public APP_URL (https://ufw.example.com): " APP_URL
if [[ -z "$APP_URL" ]]; then
  echo "APP_URL is required." >&2
  exit 1
fi

read -r -p "NPM Docker network name (e.g. nginxproxymanager_default): " NPM_NETWORK
if [[ -z "$NPM_NETWORK" ]]; then
  echo "NPM_NETWORK is required for production behind NPM." >&2
  exit 1
fi

read -r -p "GitHub owner for GHCR images (lowercase): " GHCR_OWNER
if [[ -z "$GHCR_OWNER" ]]; then
  echo "GHCR_OWNER is required." >&2
  exit 1
fi

read -r -p "Image tag to deploy (e.g. v0.1.0): " IMAGE_TAG
if [[ -z "$IMAGE_TAG" ]]; then
  echo "IMAGE_TAG is required." >&2
  exit 1
fi

POSTGRES_PASSWORD="$(openssl rand -base64 24 | tr -d '\n')"
BETTER_AUTH_SECRET="$(openssl rand -base64 32 | tr -d '\n')"
APP_ENCRYPTION_KEY="$(openssl rand -base64 32 | tr -d '\n')"

GHCR_OWNER_LOWER="$(printf '%s' "$GHCR_OWNER" | tr '[:upper:]' '[:lower:]')"

cat >"$TARGET_FILE" <<EOF
# Generated by scripts/generate-production-env.sh — keep this file secret.
# Do NOT commit to git.

APP_URL=${APP_URL}
NPM_NETWORK=${NPM_NETWORK}
IMAGE_TAG=${IMAGE_TAG}
GHCR_OWNER=${GHCR_OWNER_LOWER}
GHCR_APP_IMAGE=ghcr.io/${GHCR_OWNER_LOWER}/ufw-remote-manager:${IMAGE_TAG}
GHCR_MIGRATE_IMAGE=ghcr.io/${GHCR_OWNER_LOWER}/ufw-remote-manager-migrate:${IMAGE_TAG}

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
APP_ENCRYPTION_KEY=${APP_ENCRYPTION_KEY}
EOF

chmod 600 "$TARGET_FILE"

cat <<EOF

Created ${TARGET_FILE} (mode 600).

Next steps:
  1. Pull or build GHCR images (see docs/deploy/ghcr.md).
  2. Deploy with Portainer or:
       docker compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.ghcr.yml --env-file ${TARGET_FILE} up -d
  3. Configure NPM Proxy Host → ufw-app:3000
  4. Run: ./scripts/smoke-production.sh --env-file ${TARGET_FILE} --ghcr --app-url ${APP_URL}
  5. Open ${APP_URL}/setup and create the admin account

EOF